/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ISpatters__factory } from "./ISpatters__factory";
export { SpattersGenerator__factory } from "./SpattersGenerator__factory";
