/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISpatters,
  ISpattersInterface,
} from "../../../contracts/SpattersGenerator.sol/ISpatters";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "getCustomPalette",
    outputs: [
      {
        internalType: "string[6]",
        name: "",
        type: "string[6]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "getTokenMutations",
    outputs: [
      {
        components: [
          {
            internalType: "string",
            name: "mutationType",
            type: "string",
          },
          {
            internalType: "bytes32",
            name: "seed",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "timestamp",
            type: "uint256",
          },
        ],
        internalType: "struct MutationRecord[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "tokens",
    outputs: [
      {
        internalType: "bytes32",
        name: "mintSeed",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "mintTimestamp",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISpatters__factory {
  static readonly abi = _abi;
  static createInterface(): ISpattersInterface {
    return new Interface(_abi) as ISpattersInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ISpatters {
    return new Contract(address, _abi, runner) as unknown as ISpatters;
  }
}
