/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type MutationRecordStruct = {
  mutationType: string;
  seed: BytesLike;
  timestamp: BigNumberish;
};

export type MutationRecordStructOutput = [
  mutationType: string,
  seed: string,
  timestamp: bigint
] & { mutationType: string; seed: string; timestamp: bigint };

export interface ISpattersInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getCustomPalette"
      | "getTokenMutations"
      | "ownerOf"
      | "tokens"
      | "totalSupply"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getCustomPalette",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenMutations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getCustomPalette",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenMutations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
}

export interface ISpatters extends BaseContract {
  connect(runner?: ContractRunner | null): ISpatters;
  waitForDeployment(): Promise<this>;

  interface: ISpattersInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getCustomPalette: TypedContractMethod<
    [arg0: BigNumberish],
    [string[]],
    "view"
  >;

  getTokenMutations: TypedContractMethod<
    [arg0: BigNumberish],
    [MutationRecordStructOutput[]],
    "view"
  >;

  ownerOf: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  tokens: TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { mintSeed: string; mintTimestamp: bigint }],
    "view"
  >;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getCustomPalette"
  ): TypedContractMethod<[arg0: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTokenMutations"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [MutationRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "tokens"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { mintSeed: string; mintTimestamp: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
