/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface SpattersGeneratorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "HTML_TEMPLATE_ADDRESSES"
      | "SPATTERS_CONTRACT"
      | "STORAGE_ADDRESSES"
      | "getHtmlTemplate"
      | "getHtmlTemplateAddresses"
      | "getHtmlTemplateCount"
      | "getStorageAddress"
      | "getStorageAddresses"
      | "getStorageCount"
      | "getTemplateConfig"
      | "getTokenData"
      | "readStorageChunk"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "HTML_TEMPLATE_ADDRESSES",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "SPATTERS_CONTRACT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STORAGE_ADDRESSES",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHtmlTemplate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getHtmlTemplateAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getHtmlTemplateCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStorageAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStorageAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStorageCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTemplateConfig",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenData",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "readStorageChunk",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "HTML_TEMPLATE_ADDRESSES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SPATTERS_CONTRACT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STORAGE_ADDRESSES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHtmlTemplate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHtmlTemplateAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHtmlTemplateCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStorageAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStorageAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStorageCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTemplateConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "readStorageChunk",
    data: BytesLike
  ): Result;
}

export interface SpattersGenerator extends BaseContract {
  connect(runner?: ContractRunner | null): SpattersGenerator;
  waitForDeployment(): Promise<this>;

  interface: SpattersGeneratorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  HTML_TEMPLATE_ADDRESSES: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  SPATTERS_CONTRACT: TypedContractMethod<[], [string], "view">;

  STORAGE_ADDRESSES: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  getHtmlTemplate: TypedContractMethod<[], [string], "view">;

  getHtmlTemplateAddresses: TypedContractMethod<[], [string[]], "view">;

  getHtmlTemplateCount: TypedContractMethod<[], [bigint], "view">;

  getStorageAddress: TypedContractMethod<
    [index: BigNumberish],
    [string],
    "view"
  >;

  getStorageAddresses: TypedContractMethod<[], [string[]], "view">;

  getStorageCount: TypedContractMethod<[], [bigint], "view">;

  getTemplateConfig: TypedContractMethod<
    [],
    [
      [string, string, string[], string[]] & {
        spattersContract: string;
        generatorContract: string;
        storageAddresses: string[];
        templateAddresses: string[];
      }
    ],
    "view"
  >;

  getTokenData: TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [string, string[], string[], string[]] & {
        seed: string;
        mutationSeeds: string[];
        mutationTypes: string[];
        customPalette: string[];
      }
    ],
    "view"
  >;

  readStorageChunk: TypedContractMethod<
    [storageAddress: AddressLike],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "HTML_TEMPLATE_ADDRESSES"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "SPATTERS_CONTRACT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "STORAGE_ADDRESSES"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getHtmlTemplate"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getHtmlTemplateAddresses"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getHtmlTemplateCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStorageAddress"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getStorageAddresses"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getStorageCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTemplateConfig"
  ): TypedContractMethod<
    [],
    [
      [string, string, string[], string[]] & {
        spattersContract: string;
        generatorContract: string;
        storageAddresses: string[];
        templateAddresses: string[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenData"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [string, string[], string[], string[]] & {
        seed: string;
        mutationSeeds: string[];
        mutationTypes: string[];
        customPalette: string[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "readStorageChunk"
  ): TypedContractMethod<[storageAddress: AddressLike], [string], "view">;

  filters: {};
}
