/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as spattersGeneratorSol from "./SpattersGenerator.sol";
export type { spattersGeneratorSol };
export type { Spatters } from "./Spatters";
