/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Spatters {
  export type MintRequestStruct = {
    seeds: [BytesLike, BytesLike, BytesLike];
    timestamp: BigNumberish;
    completed: boolean;
  };

  export type MintRequestStructOutput = [
    seeds: [string, string, string],
    timestamp: bigint,
    completed: boolean
  ] & {
    seeds: [string, string, string];
    timestamp: bigint;
    completed: boolean;
  };

  export type MutationRecordStruct = {
    mutationType: string;
    seed: BytesLike;
    timestamp: BigNumberish;
  };

  export type MutationRecordStructOutput = [
    mutationType: string,
    seed: string,
    timestamp: bigint
  ] & { mutationType: string; seed: string; timestamp: bigint };
}

export interface SpattersInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CONFIRMATION_WINDOW"
      | "DEFAULT_PALETTE"
      | "GLOBAL_COOLDOWN"
      | "GOVERNANCE_DELAY"
      | "MAX_MUTATIONS"
      | "MAX_PER_WALLET"
      | "MAX_SUPPLY"
      | "OWNER_RESERVE"
      | "PROPOSAL_COOLDOWN"
      | "REQUEST_EXPIRATION"
      | "ROYALTY_BPS"
      | "WALLET_COOLDOWN"
      | "allowedMutations"
      | "approve"
      | "approveProposal"
      | "balanceOf"
      | "baseURI"
      | "canMutate"
      | "collectionLaunchDate"
      | "completeMint"
      | "confirmProposal"
      | "currentProposal"
      | "currentProposalVoters"
      | "customPalettes"
      | "deploymentTime"
      | "getAllowedMutations"
      | "getApproved"
      | "getCurrentPrice"
      | "getCurrentProposal"
      | "getCustomPalette"
      | "getPendingRequest"
      | "getTokenMutations"
      | "hasVotedForCurrentProposal"
      | "isApprovedForAll"
      | "lastGlobalMintTime"
      | "lastMintTime"
      | "lastProposalTime"
      | "mintedPerWallet"
      | "mutate"
      | "name"
      | "owner"
      | "ownerMint"
      | "ownerOf"
      | "p5jsScriptAddress"
      | "pendingRequests"
      | "proposeBaseURI"
      | "renounceOwnership"
      | "requestMint"
      | "royaltyInfo"
      | "royaltyReceiver"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "setBaseURI"
      | "setRoyaltyReceiver"
      | "setScriptAddresses"
      | "spattersScriptAddress"
      | "supportsInterface"
      | "symbol"
      | "tokenMutations"
      | "tokenURI"
      | "tokens"
      | "totalSupply"
      | "transferFrom"
      | "transferOwnership"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "ApprovalForAll"
      | "BaseURIUpdatedByCommunity"
      | "BaseURIUpdatedByOwner"
      | "MintRequested"
      | "Minted"
      | "Mutated"
      | "OwnershipTransferred"
      | "ProposalCreated"
      | "ProposalLocked"
      | "ProposalThresholdReached"
      | "RoyaltyReceiverUpdated"
      | "Transfer"
      | "VoteCast"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CONFIRMATION_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_PALETTE",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "GLOBAL_COOLDOWN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GOVERNANCE_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_MUTATIONS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_PER_WALLET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OWNER_RESERVE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROPOSAL_COOLDOWN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REQUEST_EXPIRATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROYALTY_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WALLET_COOLDOWN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allowedMutations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveProposal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "baseURI", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "canMutate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collectionLaunchDate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "completeMint",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmProposal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentProposal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentProposalVoters",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "customPalettes",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deploymentTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllowedMutations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentProposal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCustomPalette",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingRequest",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenMutations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVotedForCurrentProposal",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastGlobalMintTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastMintTime",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastProposalTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintedPerWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mutate",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerMint",
    values: [AddressLike, string[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "p5jsScriptAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRequests",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeBaseURI",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestMint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "royaltyInfo",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "royaltyReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(functionFragment: "setBaseURI", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setRoyaltyReceiver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setScriptAddresses",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "spattersScriptAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenMutations",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "CONFIRMATION_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_PALETTE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GLOBAL_COOLDOWN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GOVERNANCE_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_MUTATIONS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_PER_WALLET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_SUPPLY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "OWNER_RESERVE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROPOSAL_COOLDOWN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REQUEST_EXPIRATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROYALTY_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WALLET_COOLDOWN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowedMutations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "baseURI", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canMutate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collectionLaunchDate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentProposalVoters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "customPalettes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deploymentTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllowedMutations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCustomPalette",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenMutations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasVotedForCurrentProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastGlobalMintTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastMintTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastProposalTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintedPerWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mutate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerMint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "p5jsScriptAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeBaseURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "royaltyInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "royaltyReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBaseURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setRoyaltyReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setScriptAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "spattersScriptAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenMutations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BaseURIUpdatedByCommunityEvent {
  export type InputTuple = [newURI: string];
  export type OutputTuple = [newURI: string];
  export interface OutputObject {
    newURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BaseURIUpdatedByOwnerEvent {
  export type InputTuple = [newURI: string];
  export type OutputTuple = [newURI: string];
  export interface OutputObject {
    newURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MintRequestedEvent {
  export type InputTuple = [
    requester: AddressLike,
    seeds: [BytesLike, BytesLike, BytesLike],
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    requester: string,
    seeds: [string, string, string],
    timestamp: bigint
  ];
  export interface OutputObject {
    requester: string;
    seeds: [string, string, string];
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MintedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    minter: AddressLike,
    seed: BytesLike,
    hasCustomPalette: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    minter: string,
    seed: string,
    hasCustomPalette: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    minter: string;
    seed: string;
    hasCustomPalette: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MutatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    mutationIndex: BigNumberish,
    mutationType: string,
    seed: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    mutationIndex: bigint,
    mutationType: string,
    seed: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    mutationIndex: bigint;
    mutationType: string;
    seed: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [
    proposer: AddressLike,
    proposedURI: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    proposer: string,
    proposedURI: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    proposer: string;
    proposedURI: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalLockedEvent {
  export type InputTuple = [lockedURI: string];
  export type OutputTuple = [lockedURI: string];
  export interface OutputObject {
    lockedURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalThresholdReachedEvent {
  export type InputTuple = [proposedURI: string, timestamp: BigNumberish];
  export type OutputTuple = [proposedURI: string, timestamp: bigint];
  export interface OutputObject {
    proposedURI: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoyaltyReceiverUpdatedEvent {
  export type InputTuple = [newReceiver: AddressLike];
  export type OutputTuple = [newReceiver: string];
  export interface OutputObject {
    newReceiver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [voter: AddressLike, weight: BigNumberish];
  export type OutputTuple = [voter: string, weight: bigint];
  export interface OutputObject {
    voter: string;
    weight: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Spatters extends BaseContract {
  connect(runner?: ContractRunner | null): Spatters;
  waitForDeployment(): Promise<this>;

  interface: SpattersInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CONFIRMATION_WINDOW: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_PALETTE: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  GLOBAL_COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  GOVERNANCE_DELAY: TypedContractMethod<[], [bigint], "view">;

  MAX_MUTATIONS: TypedContractMethod<[], [bigint], "view">;

  MAX_PER_WALLET: TypedContractMethod<[], [bigint], "view">;

  MAX_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  OWNER_RESERVE: TypedContractMethod<[], [bigint], "view">;

  PROPOSAL_COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  REQUEST_EXPIRATION: TypedContractMethod<[], [bigint], "view">;

  ROYALTY_BPS: TypedContractMethod<[], [bigint], "view">;

  WALLET_COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  allowedMutations: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  approveProposal: TypedContractMethod<[], [void], "nonpayable">;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  baseURI: TypedContractMethod<[], [string], "view">;

  canMutate: TypedContractMethod<[tokenId: BigNumberish], [boolean], "view">;

  collectionLaunchDate: TypedContractMethod<[], [bigint], "view">;

  completeMint: TypedContractMethod<
    [seedChoice: BigNumberish],
    [void],
    "nonpayable"
  >;

  confirmProposal: TypedContractMethod<[], [void], "nonpayable">;

  currentProposal: TypedContractMethod<
    [],
    [
      [string, string, bigint, bigint, boolean, boolean, bigint, boolean] & {
        proposer: string;
        proposedBaseURI: string;
        proposalTime: bigint;
        totalVotesWeight: bigint;
        locked: boolean;
        thresholdReached: boolean;
        thresholdReachedTime: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;

  currentProposalVoters: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  customPalettes: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  deploymentTime: TypedContractMethod<[], [bigint], "view">;

  getAllowedMutations: TypedContractMethod<[], [string[]], "view">;

  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getCurrentPrice: TypedContractMethod<[], [bigint], "view">;

  getCurrentProposal: TypedContractMethod<
    [],
    [
      [string, string, bigint, bigint, boolean, boolean, bigint, boolean] & {
        proposer: string;
        proposedURI: string;
        proposalTime: bigint;
        totalVotes: bigint;
        locked: boolean;
        thresholdReached: boolean;
        thresholdTime: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;

  getCustomPalette: TypedContractMethod<
    [tokenId: BigNumberish],
    [string[]],
    "view"
  >;

  getPendingRequest: TypedContractMethod<
    [minter: AddressLike],
    [Spatters.MintRequestStructOutput],
    "view"
  >;

  getTokenMutations: TypedContractMethod<
    [tokenId: BigNumberish],
    [Spatters.MutationRecordStructOutput[]],
    "view"
  >;

  hasVotedForCurrentProposal: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  lastGlobalMintTime: TypedContractMethod<[], [bigint], "view">;

  lastMintTime: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  lastProposalTime: TypedContractMethod<[], [bigint], "view">;

  mintedPerWallet: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  mutate: TypedContractMethod<
    [tokenId: BigNumberish, mutationType: string],
    [void],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerMint: TypedContractMethod<
    [to: AddressLike, customPalette: string[], customSeed: BytesLike],
    [void],
    "nonpayable"
  >;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  p5jsScriptAddress: TypedContractMethod<[], [string], "view">;

  pendingRequests: TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, boolean] & { timestamp: bigint; completed: boolean }],
    "view"
  >;

  proposeBaseURI: TypedContractMethod<[newURI: string], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestMint: TypedContractMethod<[], [[string, string, string]], "payable">;

  royaltyInfo: TypedContractMethod<
    [tokenId: BigNumberish, salePrice: BigNumberish],
    [[string, bigint] & { receiver: string; royaltyAmount: bigint }],
    "view"
  >;

  royaltyReceiver: TypedContractMethod<[], [string], "view">;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setBaseURI: TypedContractMethod<[newURI: string], [void], "nonpayable">;

  setRoyaltyReceiver: TypedContractMethod<
    [newReceiver: AddressLike],
    [void],
    "nonpayable"
  >;

  setScriptAddresses: TypedContractMethod<
    [_p5jsAddress: AddressLike, _spattersAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  spattersScriptAddress: TypedContractMethod<[], [string], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  tokenMutations: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, bigint] & {
        mutationType: string;
        seed: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  tokens: TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { mintSeed: string; mintTimestamp: bigint }],
    "view"
  >;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CONFIRMATION_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_PALETTE"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "GLOBAL_COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GOVERNANCE_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_MUTATIONS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_PER_WALLET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "OWNER_RESERVE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PROPOSAL_COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REQUEST_EXPIRATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ROYALTY_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WALLET_COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "allowedMutations"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approveProposal"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "baseURI"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "canMutate"
  ): TypedContractMethod<[tokenId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "collectionLaunchDate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "completeMint"
  ): TypedContractMethod<[seedChoice: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confirmProposal"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "currentProposal"
  ): TypedContractMethod<
    [],
    [
      [string, string, bigint, bigint, boolean, boolean, bigint, boolean] & {
        proposer: string;
        proposedBaseURI: string;
        proposalTime: bigint;
        totalVotesWeight: bigint;
        locked: boolean;
        thresholdReached: boolean;
        thresholdReachedTime: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "currentProposalVoters"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "customPalettes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "deploymentTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAllowedMutations"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getCurrentPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrentProposal"
  ): TypedContractMethod<
    [],
    [
      [string, string, bigint, bigint, boolean, boolean, bigint, boolean] & {
        proposer: string;
        proposedURI: string;
        proposalTime: bigint;
        totalVotes: bigint;
        locked: boolean;
        thresholdReached: boolean;
        thresholdTime: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCustomPalette"
  ): TypedContractMethod<[tokenId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPendingRequest"
  ): TypedContractMethod<
    [minter: AddressLike],
    [Spatters.MintRequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenMutations"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [Spatters.MutationRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVotedForCurrentProposal"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastGlobalMintTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastMintTime"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastProposalTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "mintedPerWallet"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "mutate"
  ): TypedContractMethod<
    [tokenId: BigNumberish, mutationType: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerMint"
  ): TypedContractMethod<
    [to: AddressLike, customPalette: string[], customSeed: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "p5jsScriptAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingRequests"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, boolean] & { timestamp: bigint; completed: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposeBaseURI"
  ): TypedContractMethod<[newURI: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestMint"
  ): TypedContractMethod<[], [[string, string, string]], "payable">;
  getFunction(
    nameOrSignature: "royaltyInfo"
  ): TypedContractMethod<
    [tokenId: BigNumberish, salePrice: BigNumberish],
    [[string, bigint] & { receiver: string; royaltyAmount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "royaltyReceiver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBaseURI"
  ): TypedContractMethod<[newURI: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRoyaltyReceiver"
  ): TypedContractMethod<[newReceiver: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setScriptAddresses"
  ): TypedContractMethod<
    [_p5jsAddress: AddressLike, _spattersAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "spattersScriptAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenMutations"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, bigint] & {
        mutationType: string;
        seed: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "tokens"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { mintSeed: string; mintTimestamp: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "BaseURIUpdatedByCommunity"
  ): TypedContractEvent<
    BaseURIUpdatedByCommunityEvent.InputTuple,
    BaseURIUpdatedByCommunityEvent.OutputTuple,
    BaseURIUpdatedByCommunityEvent.OutputObject
  >;
  getEvent(
    key: "BaseURIUpdatedByOwner"
  ): TypedContractEvent<
    BaseURIUpdatedByOwnerEvent.InputTuple,
    BaseURIUpdatedByOwnerEvent.OutputTuple,
    BaseURIUpdatedByOwnerEvent.OutputObject
  >;
  getEvent(
    key: "MintRequested"
  ): TypedContractEvent<
    MintRequestedEvent.InputTuple,
    MintRequestedEvent.OutputTuple,
    MintRequestedEvent.OutputObject
  >;
  getEvent(
    key: "Minted"
  ): TypedContractEvent<
    MintedEvent.InputTuple,
    MintedEvent.OutputTuple,
    MintedEvent.OutputObject
  >;
  getEvent(
    key: "Mutated"
  ): TypedContractEvent<
    MutatedEvent.InputTuple,
    MutatedEvent.OutputTuple,
    MutatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalLocked"
  ): TypedContractEvent<
    ProposalLockedEvent.InputTuple,
    ProposalLockedEvent.OutputTuple,
    ProposalLockedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalThresholdReached"
  ): TypedContractEvent<
    ProposalThresholdReachedEvent.InputTuple,
    ProposalThresholdReachedEvent.OutputTuple,
    ProposalThresholdReachedEvent.OutputObject
  >;
  getEvent(
    key: "RoyaltyReceiverUpdated"
  ): TypedContractEvent<
    RoyaltyReceiverUpdatedEvent.InputTuple,
    RoyaltyReceiverUpdatedEvent.OutputTuple,
    RoyaltyReceiverUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "BaseURIUpdatedByCommunity(string)": TypedContractEvent<
      BaseURIUpdatedByCommunityEvent.InputTuple,
      BaseURIUpdatedByCommunityEvent.OutputTuple,
      BaseURIUpdatedByCommunityEvent.OutputObject
    >;
    BaseURIUpdatedByCommunity: TypedContractEvent<
      BaseURIUpdatedByCommunityEvent.InputTuple,
      BaseURIUpdatedByCommunityEvent.OutputTuple,
      BaseURIUpdatedByCommunityEvent.OutputObject
    >;

    "BaseURIUpdatedByOwner(string)": TypedContractEvent<
      BaseURIUpdatedByOwnerEvent.InputTuple,
      BaseURIUpdatedByOwnerEvent.OutputTuple,
      BaseURIUpdatedByOwnerEvent.OutputObject
    >;
    BaseURIUpdatedByOwner: TypedContractEvent<
      BaseURIUpdatedByOwnerEvent.InputTuple,
      BaseURIUpdatedByOwnerEvent.OutputTuple,
      BaseURIUpdatedByOwnerEvent.OutputObject
    >;

    "MintRequested(address,bytes32[3],uint256)": TypedContractEvent<
      MintRequestedEvent.InputTuple,
      MintRequestedEvent.OutputTuple,
      MintRequestedEvent.OutputObject
    >;
    MintRequested: TypedContractEvent<
      MintRequestedEvent.InputTuple,
      MintRequestedEvent.OutputTuple,
      MintRequestedEvent.OutputObject
    >;

    "Minted(uint256,address,bytes32,bool,uint256)": TypedContractEvent<
      MintedEvent.InputTuple,
      MintedEvent.OutputTuple,
      MintedEvent.OutputObject
    >;
    Minted: TypedContractEvent<
      MintedEvent.InputTuple,
      MintedEvent.OutputTuple,
      MintedEvent.OutputObject
    >;

    "Mutated(uint256,uint256,string,bytes32,uint256)": TypedContractEvent<
      MutatedEvent.InputTuple,
      MutatedEvent.OutputTuple,
      MutatedEvent.OutputObject
    >;
    Mutated: TypedContractEvent<
      MutatedEvent.InputTuple,
      MutatedEvent.OutputTuple,
      MutatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProposalCreated(address,string,uint256)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;

    "ProposalLocked(string)": TypedContractEvent<
      ProposalLockedEvent.InputTuple,
      ProposalLockedEvent.OutputTuple,
      ProposalLockedEvent.OutputObject
    >;
    ProposalLocked: TypedContractEvent<
      ProposalLockedEvent.InputTuple,
      ProposalLockedEvent.OutputTuple,
      ProposalLockedEvent.OutputObject
    >;

    "ProposalThresholdReached(string,uint256)": TypedContractEvent<
      ProposalThresholdReachedEvent.InputTuple,
      ProposalThresholdReachedEvent.OutputTuple,
      ProposalThresholdReachedEvent.OutputObject
    >;
    ProposalThresholdReached: TypedContractEvent<
      ProposalThresholdReachedEvent.InputTuple,
      ProposalThresholdReachedEvent.OutputTuple,
      ProposalThresholdReachedEvent.OutputObject
    >;

    "RoyaltyReceiverUpdated(address)": TypedContractEvent<
      RoyaltyReceiverUpdatedEvent.InputTuple,
      RoyaltyReceiverUpdatedEvent.OutputTuple,
      RoyaltyReceiverUpdatedEvent.OutputObject
    >;
    RoyaltyReceiverUpdated: TypedContractEvent<
      RoyaltyReceiverUpdatedEvent.InputTuple,
      RoyaltyReceiverUpdatedEvent.OutputTuple,
      RoyaltyReceiverUpdatedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "VoteCast(address,uint256)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
