import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'NFT License Agreement - Spatters',
  description: 'NFT License Agreement for Spatters NFT collection',
};

export default function NFTLicense() {
  return (
    <article className="prose prose-lg max-w-none">
      <h1 className="text-4xl font-black mb-2">NFT License Agreement</h1>
      <p className="text-sm opacity-70 mb-8">Last updated: January 2025</p>

      <section className="mb-8">
        <h2 className="text-2xl font-bold mb-4">1. Overview</h2>
        <p>
          This NFT License Agreement (&quot;License&quot;) governs the intellectual property rights associated with 
          Spatters NFTs. Spatters embraces an open and permissive approach to digital art ownership, granting 
          broad rights to everyone while maintaining the collaborative spirit of the collection.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold mb-4">2. Grant of Rights</h2>
        
        <h3 className="text-xl font-semibold mt-6 mb-3">2.1 Universal Rights (CC0-Style)</h3>
        <p>
          Spatters grants <strong>full, unrestricted commercial and non-commercial rights</strong> to the 
          artwork generated by each Spatter to <strong>everyone</strong>, regardless of whether they own the 
          NFT. This means:
        </p>
        <ul className="list-disc list-inside mt-4 space-y-2">
          <li>
            <strong>Anyone</strong> may use, copy, modify, distribute, display, and create derivative works 
            from any Spatter artwork
          </li>
          <li>
            <strong>Anyone</strong> may use Spatter artwork for commercial purposes, including selling prints, 
            merchandise, or incorporating the art into commercial products
          </li>
          <li>
            <strong>No attribution is required</strong> (though it is appreciated)
          </li>
          <li>
            <strong>No permission is needed</strong> for any use
          </li>
        </ul>

        <h3 className="text-xl font-semibold mt-6 mb-3">2.2 What the NFT Represents</h3>
        <p>
          Owning a Spatters NFT grants you:
        </p>
        <ul className="list-disc list-inside mt-4 space-y-2">
          <li>
            <strong>On-chain proof of ownership</strong> of that specific token
          </li>
          <li>
            <strong>The ability to mutate</strong> the artwork on designated dates, permanently changing it
          </li>
          <li>
            <strong>The ability to transfer or sell</strong> the NFT
          </li>
          <li>
            <strong>Historical provenance</strong> as a holder who shaped this specific artwork
          </li>
        </ul>
        <p className="mt-4">
          The NFT represents ownership of the token itself and the right to mutate it, not exclusive rights 
          to the artwork. This is intentional—Spatters celebrates open culture and the free sharing of art.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold mb-4">3. Artist Retained Rights</h2>
        <p>
          The artist (creator of Spatters) retains the same rights as everyone else—full, unrestricted rights 
          to use, display, reproduce, and commercialize any and all Spatter artwork. This includes:
        </p>
        <ul className="list-disc list-inside mt-4 space-y-2">
          <li>Displaying Spatters artwork in galleries, exhibitions, and promotional materials</li>
          <li>Using Spatters artwork in future projects or collections</li>
          <li>Creating prints, merchandise, or derivative works</li>
          <li>Showcasing the collection for portfolio or educational purposes</li>
        </ul>
        <p className="mt-4">
          The artist&apos;s rights are equal to, not greater than, those of any other person.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold mb-4">4. Transfer of NFT</h2>
        <p>
          When a Spatters NFT is transferred (sold, gifted, or otherwise conveyed), the following occurs:
        </p>
        <ul className="list-disc list-inside mt-4 space-y-2">
          <li>
            <strong>Ownership transfers:</strong> The new holder becomes the owner of the NFT and gains the 
            ability to mutate it
          </li>
          <li>
            <strong>Rights remain universal:</strong> Since rights to the artwork are granted to everyone, 
            there is nothing to &quot;transfer&quot; in terms of usage rights
          </li>
          <li>
            <strong>History is preserved:</strong> The blockchain permanently records the provenance and 
            mutation history, including all previous owners
          </li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold mb-4">5. On-Chain Nature</h2>
        <p>
          Spatters is <strong>fully on-chain</strong>. This means:
        </p>
        <ul className="list-disc list-inside mt-4 space-y-2">
          <li>
            <strong>Perpetual accessibility:</strong> The artwork code and output are stored entirely on the 
            Ethereum blockchain and will exist as long as Ethereum exists
          </li>
          <li>
            <strong>No dependency on external services:</strong> The art does not rely on external servers, 
            IPFS, or any off-chain storage
          </li>
          <li>
            <strong>Verifiable authenticity:</strong> Anyone can verify the authenticity and history of any 
            Spatter by reading the blockchain
          </li>
          <li>
            <strong>Immutable history:</strong> Every mutation and every owner is permanently recorded
          </li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold mb-4">6. Mutations and Artistic Evolution</h2>
        <p>
          The mutation system is a core feature of Spatters that allows the artwork to evolve over time:
        </p>
        <ul className="list-disc list-inside mt-4 space-y-2">
          <li>
            <strong>Mutations are permanent:</strong> Each mutation creates a new layer of the artwork that 
            becomes part of its permanent history
          </li>
          <li>
            <strong>Mutations are collaborative:</strong> The final appearance of a Spatter reflects the 
            choices of every owner who mutated it
          </li>
          <li>
            <strong>Mutations are generative:</strong> The specific outcome depends on blockchain state at 
            the time of mutation and cannot be predetermined
          </li>
          <li>
            <strong>All states are preserved:</strong> Previous versions remain viewable; mutations add to 
            rather than replace the artwork&apos;s history
          </li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold mb-4">7. Third-Party Code</h2>
        <p>
          Spatters uses the p5.js library, which is licensed under the GNU Lesser General Public License (LGPL) 
          version 2.1. The p5.js library is used unmodified and in accordance with its license terms. The LGPL 
          permits use in both open-source and proprietary applications.
        </p>
        <p className="mt-4">
          The on-chain version of p5.js used by Spatters was deployed by Art Blocks and is available on the 
          Ethereum blockchain for anyone to use.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold mb-4">8. No Warranties</h2>
        <p>
          The artwork and associated rights are provided &quot;as is&quot; without any warranties. We make no 
          representations about:
        </p>
        <ul className="list-disc list-inside mt-4 space-y-2">
          <li>The aesthetic quality or value of the artwork</li>
          <li>The functionality of the smart contract</li>
          <li>The future availability of mutation dates</li>
          <li>Any commercial potential or resale value</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold mb-4">9. Governing Law</h2>
        <p>
          This License shall be governed by the laws of the State of Delaware, United States, without regard 
          to its conflict of law provisions.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold mb-4">10. Contact</h2>
        <p>
          For questions about this License, please contact:{' '}
          <a href="mailto:spatterseth@gmail.com" className="underline hover:opacity-70">
            spatterseth@gmail.com
          </a>
        </p>
      </section>
    </article>
  );
}

