/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as spattersGeneratorSol from "./SpattersGenerator.sol";
export { Spatters__factory } from "./Spatters__factory";
